name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"
      - name: Build sources
        run: |
          go version
          go get -t -d -v ./...
          go build
      - name: Run tests
        run: go test -v
